-- AlterTable
ALTER TABLE "Household" ADD COLUMN     "baseLoad" DOUBLE PRECISION NOT NULL DEFAULT 10,
ADD COLUMN     "evDisconnected" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "forecastError" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "inverterFault" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "smartMeterOffline" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "solarIrradiance" DOUBLE PRECISION NOT NULL DEFAULT 50;
