-- AlterTable
ALTER TABLE "Household" ADD COLUMN     "currentBatterySoc" DOUBLE PRECISION NOT NULL DEFAULT 20.0,
ADD COLUMN     "simulationLastTick" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "simulationSpeed" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
ADD COLUMN     "simulationStatus" TEXT NOT NULL DEFAULT 'LIVE',
ADD COLUMN     "simulationTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
